version: '3.8'

services:
  leerkuendigungen-analysis:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: leerkuendigungen-analysis
    volumes:
      - ../output:/analysis/output
